apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image: pralavikasai/project-nodejs:latest
        ports:
          - containerPort: 3000
        env:
          - name: MONGODB_URI
            value: "mongodb://mongo:27017/retail" 
      - name: mongo
        image: mongo:latest
        ports:
          - containerPort: 27017

